services:
  frontend:
    build:
      context: . # 루트를 빌드 컨텍스트로 설정
      dockerfile: ./packages/frontend/Dockerfile
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["yarn", "dev"]

networks:
  app-network:
    driver: bridge
